// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnJkZSw3R64p5hAP98eNBgDOORbX1_WVA',
    appId: '1:718502726238:web:2a5df60c56726def6042cf',
    messagingSenderId: '718502726238',
    projectId: 'my-shop-e305a',
    authDomain: 'my-shop-e305a.firebaseapp.com',
    storageBucket: 'my-shop-e305a.firebasestorage.app',
    measurementId: 'G-9YYJ1YG4WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHqJ2vzqmK43FM82ukfuzdl4m1EuvuUEQ',
    appId: '1:718502726238:android:5c3c61df24669d1f6042cf',
    messagingSenderId: '718502726238',
    projectId: 'my-shop-e305a',
    storageBucket: 'my-shop-e305a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb7vnip11sZtU7i4k95uRfkkqULPJimMo',
    appId: '1:718502726238:ios:45fa021983083b536042cf',
    messagingSenderId: '718502726238',
    projectId: 'my-shop-e305a',
    storageBucket: 'my-shop-e305a.firebasestorage.app',
    iosBundleId: 'com.example.myShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb7vnip11sZtU7i4k95uRfkkqULPJimMo',
    appId: '1:718502726238:ios:45fa021983083b536042cf',
    messagingSenderId: '718502726238',
    projectId: 'my-shop-e305a',
    storageBucket: 'my-shop-e305a.firebasestorage.app',
    iosBundleId: 'com.example.myShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnJkZSw3R64p5hAP98eNBgDOORbX1_WVA',
    appId: '1:718502726238:web:97c0c8a78b6bd4906042cf',
    messagingSenderId: '718502726238',
    projectId: 'my-shop-e305a',
    authDomain: 'my-shop-e305a.firebaseapp.com',
    storageBucket: 'my-shop-e305a.firebasestorage.app',
    measurementId: 'G-BRCXDZJ01X',
  );
}
